UResidence/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Net;
using System.Net.Mail;

namespace UResidence.Controllers
{
    public class SuperAdminController : Controller
    {
        bool status;
        public JsonResult UpdateImage(Admin adm)
        {
            var image = adm.Image;
            bool status = false;
            int id = adm.Id;
            if (image != null)
            {
                if (image.ContentLength > 0)
                {
                    var fileName = Path.GetFileNameWithoutExtension(image.FileName);
                    var extension = Path.GetExtension(image.FileName);
                    string imagefileName = Path.GetFileName(image.FileName);
                    string folderPath = Path.Combine(Server.MapPath("~/Content/SuperAdminImages"), imagefileName);
                    string finalpath = "";
                    if (System.IO.File.Exists(folderPath))
                    {
                       
                        for (int i = 1; System.IO.File.Exists(folderPath); i++)
                        {
                            folderPath = Path.Combine(Server.MapPath("~/Content/SuperAdminImages"), fileName + "_" + i.ToString() + extension);
                            string folderpath1 = "~/Content/SuperAdminImages/" + fileName + "_" + i.ToString() + extension;
                            finalpath = folderpath1;
                        }
                        image.SaveAs(folderPath);
                    }
                    else
                    {
                        string folderpath1 = "~/Content/SuperAdminImages/" + fileName + extension;
                        finalpath = folderpath1;
                        image.SaveAs(folderPath);
                    }

                    Admin a = new Admin
                    {
                        Id = id,
                        URL = finalpath
                    };


                    status = UResidence.AdminController.UpdateDP(a);
                }

            }
            return new JsonResult
            {
                Data = status,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

        }

        public static string Hash(string p)
        {
            SHA1CryptoServiceProvider sh = new SHA1CryptoServiceProvider();
            UTF8Encoding utf8 = new UTF8Encoding();
            string hash = BitConverter.ToString(sh.ComputeHash(utf8.GetBytes(p.ToString())));
            return hash;
        }


        private void SendEmail(string email1, string pass)
        {
            var fromAddress = new MailAddress("uresidence04@gmail.com", "URESIDENCE");
            var toAddress = new MailAddress(email1, "To Name");
            const string fromPassword = "uresidence";
            const string subject = "PalmDale Heights Condominium";

            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
            };
            using (var message = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = "Account Information" + "\n" + "Username :" + email1 + "\n"
                + "Password :" + pass
            })
            {

                smtp.Send(message);

            }
        }


      

        public ActionResult SuperAdminView()
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            int level = Convert.ToInt32(Session["Level"]);
            if (level <= 7)
            {
                Admin a = new Admin();
                a = UResidence.AdminController.GetIdAdmin(Session["UID"].ToString());
                Session["URLL"] = a.URL;
            }
            List<Admin> adminList = UResidence.AdminController.GetAll();
            return View(adminList);
        }


        public ActionResult SuperAdminAdd()
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            int level = Convert.ToInt32(Session["Level"]);
            if (level <= 7)
            {
                Admin a = new Admin();
                a = UResidence.AdminController.GetIdAdmin(Session["UID"].ToString());
                Session["URLL"] = a.URL;
            }
            return View();
        }


        [HttpPost]
        public ActionResult SuperAdminAdd(Admin adm, int typeadmin)
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            string hash;
            string pass = adm.Bdate.ToShortDateString();
            int typea = typeadmin;
            hash = Hash(pass);
            List<UserLogin> listUser = UResidence.UserController.GetAll(adm.Email);

            if (listUser.Count == 0)
            {
                string[] err = new string[] { };
                if (adm.Validate(out err))
                {
                    Admin ad = new Admin()
                    {
                        Fname = adm.Fname,
                        Mname = adm.Mname,
                        Lname = adm.Lname,
                        Bdate = adm.Bdate,
                        CelNo = adm.CelNo,
                        Email = adm.Email,
                        Deleted = "0",
                        URL = "~/Content/AdminImages/user.png"
                    };

                    UResidence.AdminController.Insert(ad);

                    Admin admi = new Admin();
                    admi = UResidence.AdminController.GetEmailAdmin(adm.Email.ToString());
                    int adminid = admi.Id;

                    UserLogin ull = new UserLogin
                    {                      
                        Username = adm.Email,
                        Hash = hash,
                        CreatedBy = "",
                        ModifyBy = "",
                        DateCreated = DateTime.Now,
                        Level = typea,
                        Locked = 0,
                        LastLogin = DateTime.Now
                    };


                    UResidence.UserController.Insert(ull);
                    SendEmail(adm.Email, pass);
                    status = true;
                    ViewBag.AddMessage = status;
                    SuperAdminView();
                    return View("SuperAdminView");
                }
                else
                {
                    string script = "<script type = 'text/javascript'>alert('There is an Existing Admin!Please try Again.');</script>";
                    Response.Write(script);
                    ViewBag.ErrorMessage = FixMessages(err);
                    status = false;

                }

                ViewBag.AddMessage = status;

            }
            return View();

        }



        public ActionResult SuperAdminEdit()
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            return View();
        }
        [HttpGet]
        public ActionResult SuperAdminEdit(int id)
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            int level = Convert.ToInt32(Session["Level"]);
            if (level <= 7)
            {
                Admin a = new Admin();
                a = UResidence.AdminController.GetIdAdmin(Session["UID"].ToString());
                Session["URLL"] = a.URL;
            }
            string i = id.ToString();
            if (ModelState.IsValid)
            {
                Admin adm = UResidence.AdminController.GetbyIDEdit(i);
                return View(adm);
            }
            return View("SuperAdminEdit");
        }

        [HttpPost]
        public ActionResult SuperAdminEdit(Admin adm)
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            string[] err = new string[] { };
            if (adm.Validate(out err))
            {
                status = UResidence.AdminController.Update(adm);
                if (status == true)
                {
                    ViewBag.UpdateMessage = status;
                    SuperAdminView();
                    return View("SuperAdminView");
                }
                else
                {
                    ViewBag.UpdateMessage = status;
                    return View();
                }
            }
            else
            {
                ViewBag.ErrorMessages = FixMessages(err);
            }
            ViewBag.UpdateMessage = true;
            return View();
        }


        public ActionResult Delete(int id)
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            string delete = "1";
            Admin am = new Admin()
            {
                Id = id,
                Deleted = delete
            };
            status = UResidence.AdminController.UpdateDelete(am);
            if (status == true)
            {

                SuperAdminView();
            }
            ViewBag.DeleteStatus = status;
            return View("SuperAdminView");
        }

        public string FixMessages(string[] err)
        {
            string errors = "Please check the following: <br/>";
            foreach (string er in err) errors += (er + "<br/>");
            return errors;
        }
    }
}

UResidence/Views/SuperAdmin/SuperAdminAdd.cshtml
@model UResidence.Admin

@{
	Layout = "/Views/Layout/SuperAdminLayout.cshtml";
	ViewBag.Title = "Registration";
}



<html>

<head>



	<style>

		.col-25 {
			float: left;
			width: 25%;
			margin-top: 6px;
		}


		.col-75 {
			float: left;
			width: 75%;
			margin-top: 6px;
		}

		label {
			padding: 12px 12px 12px 0;
			display: inline-block;
		}

		.row:after {
			content: "";
			display: table;
			clear: both;
		}

		.button {
			padding: 15px 25px;
			font-size: 15px;
			text-align: center;
			cursor: pointer;
			outline: none;
			color: #fff;
			background-color: #18ac6f;
			border: none;
			border-radius: 5px;
		}



			.button:hover {
				background-color: #46bc8b;
			}

		.containerAdmin {
			padding-left: 150px;
		}
	</style>
</head>


<body>


	<br />
	<br />
	<br />

	<div class="containerAdmin">
		<h2>Admin</h2>
		@using (Html.BeginForm("SuperAdminAdd", "SuperAdmin", FormMethod.Post))
		{
			@Html.AntiForgeryToken()

			<div class="form-horizontal">

				<hr />
				@Html.ValidationSummary(true, "", new { @class = "text-danger" })

			


				<div class="row">
					<div class="col-25">

						<label for="First Name">First Name :</label>

					</div>

					<div class="col-75">
						@Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
						@Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })


					</div>
				</div>



				

				<div class="row">
					<div class="col-25">

						<label for="Middle Name">Middle Name :</label>

					</div>

					<div class="col-75">
						@Html.EditorFor(model => model.Mname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
						@Html.ValidationMessageFor(model => model.Mname, "", new { @class = "text-danger" })


					</div>
				</div>




			



				<div class="row">
					<div class="col-25">

						<label for="Last Name">Last Name :</label>

					</div>

					<div class="col-75">
						@Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
						@Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })


					</div>
				</div>



			


				<div class="row">
					<div class="col-25">

						<label for="Bdate">Birthdate :</label>

					</div>

					<div class="col-75">
						@Html.EditorFor(model => model.Bdate, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
						@Html.ValidationMessageFor(model => model.Bdate, "", new { @class = "text-danger" })

					</div>
				</div>





				<div class="row">
					<div class="col-25">

						<label for="Cel">Cellphone no. :</label>

					</div>

					<div class="col-75">
						@Html.EditorFor(model => model.CelNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
						@Html.ValidationMessageFor(model => model.CelNo, "", new { @class = "text-danger" })

					</div>
				</div>





				<div class="row">
					<div class="col-25">

						<label for="Email">Email :</label>

					</div>

					<div class="col-75">
						@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
						@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })


					</div>
				</div>

				<div class="row">
					<div class="col-25">

						<label for="Email">Type of Admin :</label>

					</div>

					<div class="col-75">
						<select class="form-control" name="typeadmin" id="typeadmin">
							<option value="2">Finance Admin</option>
							<option value="5">Registration Admin</option>
							<option value="4">Reservation Admin</option>
							<option value="1">Boss Manager</option>
							<option value="6">Security Guard Admin</option>
							<option value="0">Super Admin</option>
						</select>


					</div>
				</div>


				<input id="btnSave" type="submit" value="Save" class="button" />
				<a href="AdminView" class="button">Cancel</a>
			</div>


			<div id="aerror" class="alert alert-danger collapse">
				<a href="#" class="close" data-dismiss="alert">&times;</a>
				<strong>Error!</strong> There is a problem submitting your form
			</div>
			<div id="asuccess" class="alert alert-success collapse">
				<strong>Success!</strong> You have successfully added a Admin
			</div>
			if (ViewBag.Message != null)
			{
				if (ViewBag.Message == true)
				{
					<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
					</script>
					<script type="text/javascript">
						$(document).ready(function () {

							$('#asuccess').show('fade');

							setTimeout(function () {
								$('#asuccess').hide('fade');
							}, 2000);


						});
					</script>

				}

				else
				{
					<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
					</script>
					<script type="text/javascript">
						$(document).ready(function () {

							$('#aerror').show('fade');

							setTimeout(function () {
								$('#aerror').hide('fade');
							}, 2000);


						});

					</script>
				}

			}



		}
	</div>
</body>
</html>
@Scripts.Render("~/bundles/jqueryval")  

UResidence/Views/SuperAdmin/SuperAdminEdit.cshtml
@model UResidence.Admin

@{
	Layout = "/Views/Layout/SuperAdminLayout.cshtml";
	ViewBag.Title = "SuperAdminEdit";
}



<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />


    <style>

        .col-25 {
            float: left;
            width: 25%;
            margin-top: 6px;
        }


        .col-75 {
            float: left;
            width: 75%;
            margin-top: 6px;
        }

        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        .button {
            padding: 15px 25px;
            font-size: 15px;
            text-align: center;
            cursor: pointer;
            outline: none;
            color: #fff;
            background-color: #18ac6f;
            border: none;
            border-radius: 5px;
        }



            .button:hover {
                background-color: #46bc8b;
            }

        .containerAdmin {
            padding-left: 150px;
        }
    </style>
</head>

<body>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <div class="containerAdmin">
      
        @using (Html.BeginForm("SuperAdminEdit", "SuperAdmin", FormMethod.Post))
        {
            @Html.AntiForgeryToken()





            <div class="form-horizontal">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                <div class="container">


                    <div class="panel panel-collapse">
                        <div class="panel-heading" style="background-color:  #1C2331">
                            <font color="white"> <h3 class="panel-title"> Edit Users Information </h3></font>
                        </div>




                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="First Name">First Name :</label>

                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })


                                </div>
                            </div>
                        </div>





                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Middle Name">Middle Name :</label>

                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Mname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Mname, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>





                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Last Name">Last Name :</label>


                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })


                                </div>
                            </div>
                        </div>






                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Bdate">Birthdate :</label>


                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Bdate, new { htmlAttributes = new { @class = "form-control", @required = "required", @max = "9999-12-31" } })
                                    @Html.ValidationMessageFor(model => model.Bdate, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>






                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Cel">Cellphone no. :</label>



                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.CelNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CelNo, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>






                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Email">Email Address :</label>



                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>



                        <input type="submit" value="Save" class="button" />
                        <a href="@Url.Action("SuperAdminView","SuperAdmin")" class="button">Cancel</a>
                    </div>
                </div>
            </div>

        }
    </div>

</body>
</html>
@Scripts.Render("~/bundles/jqueryval")

UResidence/Views/SuperAdmin/SuperAdminView.cshtml
@model List<UResidence.Admin>

@{
    Layout = "/Views/Layout/BossManagerLayout.cshtml";
    ViewBag.Title = "AdminView";



}



<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

</head>



@using (Html.BeginForm("SuperAdminView", "SuperAdmin", FormMethod.Post))
{
	@Html.AntiForgeryToken()



<div class="container">

    <br />
    <br />
  

    <div class="panel panel-default">
        <div class="panel-heading" style="background-color:  #1C2331">
            <font color="white"> <h3 class="panel-title"> List of Users </h3></font>
        </div>

        <div class=" panel-body">
            <div class="table-responsive">

                <table class=" table table-bordered table-striped">

                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Middle Name</th>
                            <th>Last Name</th>
                            <th>Birthdate</th>
                            <th>Cellphone No.</th>
                            <th>Email Address</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (Admin a in Model)
                        {

                            <tr>

                                <td>@Html.DisplayFor(model => a.Fname)</td>
                                <td>@Html.DisplayFor(model => a.Mname)</td>
                                <td>@Html.DisplayFor(model => a.Lname)</td>
                                <td>@Html.DisplayFor(model => a.Bdate)</td>
                                <td>@Html.DisplayFor(model => a.CelNo)</td>
                                <td>@Html.DisplayFor(model => a.Email)</td>
                                <td>
                                    <a class="btn btn-primary" href="@Url.Action("SuperAdminEdit", "SuperAdmin", new { id = Convert.ToInt32(a.Id) })"><i class="glyphicon glyphicon-edit"></i></a>
                                    <a class="btn btn-danger" href="@Url.Action("Delete", "SuperAdmin", new { id = Convert.ToInt32(a.Id) })"><i class="glyphicon glyphicon-trash"></i> </a>
                                </td>
                            </tr>


                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="btn-link">

        <a href="@Url.Action("SuperAdminAdd", "SuperAdmin")"><input id="btnAdd" type="button" value="ADD NEW ADMIN" style="margin-left:150px;" class="btn btn-success" /></a>

    </div>
</div>



        <div id="auerror" class="alert alert-danger collapse">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>Error!</strong> There is a problem updating the Admin
        </div>
        <div id="ausuccess" class="alert alert-success collapse">
            <strong>Success!</strong> You have successfully updated the Admin
        </div>


        <div id="aerror" class="alert alert-danger collapse">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>Error!</strong> There is a problem deleting the Admin
        </div>
        <div id="asuccess" class="alert alert-success collapse">
            <strong>Success!</strong> You have successfully deleted the Admin
        </div>


        <div id="aaerror" class="alert alert-danger collapse">
            <a href="#" class="close" data-dismiss="alert">&times;</a>
            <strong>Error!</strong> There is a problem submitting your form
        </div>
        <div id="aasuccess" class="alert alert-success collapse">
            <strong>Success!</strong> You have successfully added a Admin
        </div>

        if (ViewBag.DeleteStatus != null)
        {
        if (ViewBag.DeleteStatus == true)
        {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
        </script>
        <script type="text/javascript">
            $(document).ready(function () {

                $('#asuccess').show('fade');

                setTimeout(function () {
                    $('#asuccess').hide('fade');
                }, 2000);
            });
        </script>
        }

        else
        {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
        </script>
        <script type="text/javascript">
            $(document).ready(function () {

                $('#aerror').show('fade');

                setTimeout(function () {
                    $('#aerror').hide('fade');
                }, 2000);


            });
        </script>
        }
        }

        if (ViewBag.UpdateMessage != null)
        {
        if (ViewBag.UpdateMessage == true)
        {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
        </script>
        <script type="text/javascript">
            $(document).ready(function () {

                $('#ausuccess').show('fade');

                setTimeout(function () {
                    $('#ausuccess').hide('fade');
                }, 2000);


            });
        </script>
        }

        else
        {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
        </script>
        <script type="text/javascript">
            $(document).ready(function () {

                $('#auerror').show('fade');

                setTimeout(function () {
                    $('#auerror').hide('fade');
                }, 2000);


            });
        </script>
        }
        }

        if (ViewBag.AddMessage != null)
        {
        if (ViewBag.AddMessage == true)
        {

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
        </script>
        <script type="text/javascript">

            $(document).ready(function () {

                $('#aasuccess').show('fade');

                setTimeout(function () {
                    $('#aasuccess').hide('fade');
                }, 20000);

            });
        </script>
        }

        else
        {
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
        </script>
        <script type="text/javascript">

            $(document).ready(function () {

                $('#aaerror').show('fade');

                setTimeout(function () {
                    $('#aaerror').hide('fade');
                }, 2000);


            });
        </script>

        }

        }
        }