UResidence/Controllers/OwnerController.cs
using System;
using System.Collections.Specialized;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Security.Cryptography;
using System.Text;
using System.IO;
using System.Net;
using System.Net.Mail;
using Microsoft.Reporting.WebForms;

namespace UResidence.Controllers
{

    public class OwnerController : Controller
    {
        bool status;

        // GET: Owner
        public ActionResult OwnerAdd()
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            int level = Convert.ToInt32(Session["Level"]);

            if (level <= 7)
            {
                Admin a = new Admin();
                a = UResidence.AdminController.GetIdAdmin(Session["UID"].ToString());
                Session["URLL"] = a.URL;
            }
            return View();
        }
        public ActionResult GetOwner()
        {
            List<Owner> ret = new List<Owner>();
            ret = UResidence.OwnerController.GetAll();
            return Json(new { data = ret }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetOwnerS(Owner data)
        {
            Owner ret = new Owner();
            ret = UResidence.OwnerController.GETID(data.Id);
            return new JsonResult { Data = ret ,JsonRequestBehavior=JsonRequestBehavior.AllowGet};
        }

        private bool SendEmail(string email1, string pass)
        {
            try
            {
                var fromAddress = new MailAddress("uresidence04@gmail.com", "URESIDENCE");
                var toAddress = new MailAddress(email1, "To Name");
                const string fromPassword = "uresidence";
                const string subject = "PalmDale Heights Condominium";

                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
                };
                using (var message = new MailMessage(fromAddress, toAddress)
                {
                    Subject = subject,
                    Body = "Account Information" + "\n" + "Username :" + email1 + "\n"
                    + "Password :" + pass
                })
                {

                    smtp.Send(message);

                }
                return true;
            }
            catch(Exception)
            {
                string script = "<script type = 'text/javascript'>alert('The email account that you tried to reach does not exist');</script>";
                Response.Write(script);
                return false;
            }
        }

        [HttpPost]
        public ActionResult OwnerAdd(Owner owe, HttpPostedFileBase Image1)
        {
            if (Session["Level"] == null)
            {
                return Redirect("~/Login");
            }
            try
            {
                string finalpath = "";
                var image = Image1;
                bool status = false;
                if (image != null)
                {
                    if (image.ContentLength > 0)
                    {
                        var fileName = Path.GetFileNameWithoutExtension(image.FileName);
                        var extension = Path.GetExtension(image.FileName);
                        string imagefileName = Path.GetFileName(image.FileName);
                        string folderPath = Path.Combine(Server.MapPath("~/Content/OwnerImages"), imagefileName);

                        if (System.IO.File.Exists(folderPath))
                        {
                            
                            for (int i = 1; System.IO.File.Exists(folderPath); i++)
                            {
                                folderPath = Path.Combine(Server.MapPath("~/Content/OwnerImages"), fileName + "_" + i.ToString() + extension);
                                string folderpath1 = "~/Content/OwnerImages/" + fileName + "_" + i.ToString() + extension;
                                finalpath = folderpath1;
                            }
                            image.SaveAs(folderPath);
                        }
                        else
                        {
                            string folderpath1 = "~/Content/OwnerImages/" + fileName + extension;
                            finalpath = folderpath1;
                            image.SaveAs(folderPath);


                        }
                    }
                }

                string hash;
                string pass = owe.Bdate.ToShortDateString();
                hash = Hash(pass);

                List<Owner> o1 = new List<Owner>();
                o1 = UResidence.OwnerController.GetOwnerReserve(owe.BldgNo, owe.UnitNo);
                if (o1.Count == 0)
                {
                    List<UserLogin> listUser = UResidence.UserController.GetAll(owe.Email);
                    UserLogin ul = new UserLogin
                    {
                        Username = owe.Email,
                        Hash = hash,
                        CreatedBy = "",
                        ModifyBy = "",
                        DateCreated = DateTime.Now,
                        Level = 1,
                        Locked = 1,
                        LastLogin = DateTime.Now
                    };
                    if (listUser.Count == 0)
                    {
                        string[] err = new string[] { };
                        if (owe.Validate(out err))
                        {
                            status = SendEmail(owe.Email, pass);
                            if (status == true)
                            {
                                if (image != null)
                                {
                                    Owner ow = new Owner()
                                    {

                                        BldgNo = owe.BldgNo,
                                        UnitNo = owe.UnitNo,
                                        Fname = owe.Fname,
                                        Mname = owe.Mname,
                                        Lname = owe.Lname,
                                        Bdate = owe.Bdate,
                                        CelNo = owe.CelNo,
                                        Email = owe.Email,
                                        Deleted = "0",
                                        URL = "~/Content/OwnerImages/user.png",
                                        Form = finalpath,
                                        ENo = owe.ENo,
                                        EName = owe.EName,
                                        EAddress = owe.EAddress,
                                        Address = owe.Address
                                    };
                                    status = UResidence.OwnerController.Insert(ow);
                                }
                                else
                                {
                                    Owner ow = new Owner()
                                    {

                                        BldgNo = owe.BldgNo,
                                        UnitNo = owe.UnitNo,
                                        Fname = owe.Fname,
                                        Mname = owe.Mname,
                                        Lname = owe.Lname,
                                        Bdate = owe.Bdate,
                                        CelNo = owe.CelNo,
                                        Email = owe.Email,
                                        Deleted = "0",
                                        URL = "~/Content/OwnerImages/user.png",
                                        Form = "~/Content/OwnerImages/noimage.jpeg",
                                        ENo = owe.ENo,
                                        EName = owe.EName,
                                        EAddress = owe.EAddress,
                                        Address = owe.Address


                                    };

                                    status = UResidence.OwnerController.Insert(ow);
                                }


                                string email = owe.Email;
                                Owner owee = UResidence.OwnerController.GetEmailOwner(email);
                                Residence r = new Residence()
                                {
                                    OwnerNo = owee.Id,
                                    TenantNo = 0
                                };
                                status = UResidence.ResidenceController.Insert(r);

                                int ownerid = owee.Id;

                                UserLogin ull = new UserLogin
                                {
                                    Username = owe.Email,
                                    Hash = hash,
                                    CreatedBy = "",
                                    ModifyBy = "",
                                    DateCreated = DateTime.Now,
                                    Level = 8,
                                    Locked = 0,
                                    LastLogin = DateTime.Now
                                };

                                status = UResidence.UserController.Insert(ull);
                                if (status == true)
                                {
                                    List<UserLogin> ul2 = new List<UserLogin>();
                                    ul2 = UserController.GetAll(owe.Email);
                                    if (ul2.Count > 0)
                                    {

UResidence/Views/Owner/OwnerAdd.cshtml
@model UResidence.Owner

@{
    ViewBag.Title = "OwnerAdd";
    Layout = "/Views/Layout/AdminLayout.cshtml";

}
@*Scripts for dropdown*@
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<html>

<head>



	<style>

		.col-25 {
			float: left;
			width: 25%;
			margin-top: 6px;
		}


		.col-75 {
			float: left;
			width: 75%;
			margin-top: 6px;
		}

		label {
			padding: 12px 12px 12px 0;
			display: inline-block;
		}

		.row:after {
			content: "";
			display: table;
			clear: both;
		}

		.button {
			padding: 15px 25px;
			font-size: 15px;
			text-align: center;
			cursor: pointer;
			outline: none;
			color: #fff;
			background-color: #18ac6f;
			border: none;
			border-radius: 5px;
		}



			.button:hover {
				background-color: #46bc8b;
			}


		.containerAdmin {
			padding-left: 150px;
		}
	</style>
</head>


<body>

	<br />
	<br />
	<br />


	<div class="containerAdmin">
		<h2>New Owner</h2>

		@using (Html.BeginForm("OwnerAdd", "Owner", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
			@Html.AntiForgeryToken()



		<div class="form-horizontal">

			<hr />
			@Html.ValidationSummary(true, "", new { @class = "text-danger" })


			<div class="row">
				<div class="col-25">

					<label for="First Name">First Name :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })


				</div>
			</div>


			<div class="row">
				<div class="col-25">

					<label for="Middle Name">Middle Name :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.Mname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.Mname, "", new { @class = "text-danger" })


				</div>
			</div>


			<div class="row">
				<div class="col-25">

					<label for="Last Name">Last Name :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })


				</div>
			</div>


			<div class="row">
				<div class="col-25">

					<label for="Birth Date">Birthdate :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.Bdate, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.Bdate, "", new { @class = "text-danger" })


				</div>
			</div>


			<div class="row">
				<div class="col-25">

					<label for="Cel no">Cellphone no. :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.CelNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.CelNo, "", new { @class = "text-danger" })


				</div>
			</div>

			<div class="row">
				<div class="col-25">

					<label for="Cel no">Email Address :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })


				</div>
			</div>

			<div class="row">
				<div class="col-25">

					<label for="Cel no">Building no. :</label>

				</div>

                <div class="col-75">
                    @Html.DropDownListFor(model => model.BldgNo, new List<SelectListItem>
    {
                        new SelectListItem() {Text = "1", Value="1"},
                        new SelectListItem() {Text = "2", Value="2"},
                        new SelectListItem() {Text = "3", Value="3"},
                        new SelectListItem() {Text = "4", Value="4"},
                        new SelectListItem() {Text = "5", Value="5"},
                        new SelectListItem() {Text = "6", Value="6"}
                     }, new { @class = "form-control"})
                    @Html.ValidationMessageFor(model => model.BldgNo, "", new { @class = "text-danger" })
                </div>
			</div>

			<div class="row">
				<div class="col-25">

					<label for="Cel no">Unit no. :</label>

				</div>

				<div class="col-75">
					@Html.EditorFor(model => model.UnitNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
					@Html.ValidationMessageFor(model => model.UnitNo, "", new { @class = "text-danger" })


				</div>
			</div>



			<div class="row">
				<div class="col-25">
					<p>
						<label>Registration Form :</label>
					</p>
				</div>
				<input type="file" id="Image1" name="Image1" />

			</div>


			<br />
			<br />
			<input type="submit" value="Save" class="button" />
			<a href="OwnerView" class="button">Cancel</a>




		</div>

		}
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
		</script>


	</div>
</body>
</html>

UResidence/Views/Owner/OwnerEdit.cshtml
@model UResidence.Owner

@{ 

    ViewBag.Title = "AdminView";
    if (Convert.ToInt32(Session["Level"]) == 1)
    {
        Layout = "/Views/Layout/BossManagerLayout.cshtml";
    }
    else if (Convert.ToInt32(Session["Level"]) == 0)
    {
        Layout = "/Views/Layout/SuperAdminLayout.cshtml";
    }
    else
    {
        Layout = "/Views/Layout/AdminLayout.cshtml";
    }
}



<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <style>


        label {
            padding: 12px 12px 12px 0;
            display: inline-block;
        }

        .row:after {
            content: "";
            display: table;
            clear: both;
        }

        .button {
            padding: 15px 25px;
            font-size: 15px;
            text-align: center;
            cursor: pointer;
            outline: none;
            color: #fff;
            background-color: #18ac6f;
            border: none;
            border-radius: 5px;
        }



            .button:hover {
                background-color: #46bc8b;
            }

        /*.containerAdmin {
            padding-left: 150px;
        }*/
    </style>
</head>

<body>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <div class="containerAdmin">



        @using (Html.BeginForm("OwnerEdit", "Owner", FormMethod.Post))
        {
            @Html.AntiForgeryToken()



            <div class="form-horizontal">



                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.LoginId)


                <div class="container">


                    <div class="panel panel-collapse">
                        <div class="panel-heading" style="background-color:  #1C2331">
                            <font color="white"> <h3 class="panel-title"> Update Owner Information </h3></font>
                        </div>



                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="First Name">First Name :</label>

                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })


                                </div>
                            </div>
                        </div>



                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Middle Name">Middle Name :</label>

                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Mname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Mname, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>





                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Last Name">Last Name :</label>


                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })


                                </div>
                            </div>
                        </div>




                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Bdate">Birthdate :</label>


                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Bdate, new { htmlAttributes = new { @class = "form-control", @required = "required", @max = "9999-12-31" } })
                                    @Html.ValidationMessageFor(model => model.Bdate, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>






                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Cel">Cellphone no. :</label>



                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.CelNo, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.CelNo, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>






                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Email">Email Address :</label>



                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>






                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Bldg no.">Building No. :</label>



                                <div class="col-sm-6">
                                    @Html.DropDownListFor(model => model.BldgNo, new List<SelectListItem>
                                                 {
                                                   new SelectListItem() {Text = "1A", Value="1A"},
                                                                                 new SelectListItem() {Text = "1B", Value="1B"},
                                                                                 new SelectListItem() {Text = "1C", Value="1C"},
                                                                                 new SelectListItem() {Text = "2A", Value="2A"},
                                                                                 new SelectListItem() {Text = "2B", Value="2B"},
                                                                                 new SelectListItem() {Text = "2C", Value="2C"},
                                                  }, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.BldgNo, "", new { @class = "text-danger" })
                                    @Html.ValidationMessageFor(model => model.BldgNo, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>








                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4" for="Unit no.">Unit No. :</label>



                                <div class="col-sm-6">
                                    @Html.EditorFor(model => model.UnitNo, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                                    @Html.ValidationMessageFor(model => model.UnitNo, "", new { @class = "text-danger" })

                                </div>
                            </div>
                        </div>







                        <div class="col-sm-12">
                            <div class="form-group">

                                <label class="col-sm-4">Registration Form :</label>



                                <div class="col-sm-6">
                                    <button type="button" class="btn btn-info" id="btnUpdateImage1" name="btnUpdateImage1" data-dismiss="modal">Insert Image</button>

                                </div>
                            </div>
                        </div>




                        <div class="container">
                            <div class="modal fade" id="updateImageModal1" role="dialog">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                                        </div>
                                        <div class="modal-body">
                                            <label>Registration Form: </label><input type="file" id="image1" name="image1" />
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-success" id="btnUpdate" name="btnUpdate" onclick="UpdateImage1(@Model.Id)">Update</button>
                                            <button type="button" class="btn btn-danger" id="btnCloseImage" name="btnCloseImage" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="pull-right">
                            <input type="submit" value="Save Changes" class="button" />
                            <a href="@Url.Action("OwnerView","Owner")" class="button">Cancel</a>

                        </div>
                    </div>
                </div>
            </div>

        }
        <br />
    </div>
</body>
</html>

<script>
    $(document).ready(function () {
        $('[type="date"]').prop('max', function () {
            return new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];
        });
    });
    function UpdateImage1(id) {
        var tid = id;

        var file1 = $("#image1").get(0).files;
        var data = new FormData();
        data.append("Image1", file1[0]);
        data.append("Id", tid);

        $.ajax({
            type: "POST",
            url: "/Owner/UpdateImageForm/",
            data: data,
            contentType: false,
            processData: false,
            success: function (data) {
                if (data == true) {
                    alert('Success');
                    window.location.href = window.location.href + "?rnd=" + Math.random()

                }
            },
            error: function (error) {
                alert(error);
            }
        });
	}


	//$("form").submit(function (e) {
	//	var today = new Date();
	//	var bdate = document.getElementById('Bdate').value
	//	var date1 = new Date(bdate);
	//	var age = today.getFullYear() - date1.getFullYear();
	//	var m = today.getMonth() + 1 - date1.getMonth() + 1;
	//	var d = today.getDate() - date1.getDate();

	//	if (age < 18 || m < 0) {
	//		alert("18 Years and above only");
	//		e.preventDefault();
	//	}
	//});

    $('#btnUpdateImage1').click(function () {

        $('#updateImageModal1').modal();
    }
    );
</script>